### ISSUE TITLE
Order of parameters for onEffect()

### ISSUE THREAD

**Issue by fkereki** [nanxiaobei/react-split-components#3]
I'd recommend changing the order of arguments for onEffect() -- the first should be the function (which is always required) and the second the list of variables to watch. The list should default to `[]`. This is more aligned with the usage of `useEffect()` and lets you omit the variables.

**Comment by nanxiaobei** [comment]
Thank you for your suggestion. There are 3 reasons why I didn't do this:

1. If like `useEffect`, ESLint plugin support is required.

2. Data inside `onEffect` are reactive, so no necessary to use `deps` to solve the closure problem.

3. Listen to one data will make the code clearer, and clearly know the chain reaction caused by which data.
